import { readFile, writeFile, mkdir } from "node:fs/promises";

const artifacts = {
  MockUSDT: "contracts/out/MockUSDT.sol/MockUSDT.json",
  KavlingRegistry: "contracts/out/KavlingRegistry.sol/KavlingRegistry.json",
  KavlingPropertyVault: "contracts/out/KavlingPropertyVault.sol/KavlingPropertyVault.json",
};

const output = {};
for (const [name, path] of Object.entries(artifacts)) {
  const artifact = JSON.parse(await readFile(path, "utf8"));
  output[name] = {
    abi: artifact.abi,
    bytecode: artifact.bytecode.object,
  };
}

await mkdir("frontend/deploy", { recursive: true });
await writeFile(
  "frontend/deploy/manifest.js",
  `// Generated by scripts/export_browser_artifacts.mjs after forge build.\nexport const artifacts = ${JSON.stringify(output)};\n`,
);
